---
- name: "Ensure repository for {{ puppet_server_package }} is installed"
  ansible.builtin.apt:
    deb: "{{ puppet_release_deb }}"
    state: present
  register: puppet_release_deb_install

- name: "Update apt cache if necessary"
  ansible.builtin.apt:
    update_cache: true
  when: puppet_release_deb_install.changed

- name: "Ensure {{ r10k_package }} is installed"
  ansible.builtin.package:
    name:
      - "{{ r10k_package }}"
    state: present
