---
- name: "Include installation variables for {{ ansible_facts['os_family'] }}"
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}-vars.yml"

- name: "Include installation tasks for {{ ansible_facts['os_family'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] }}-tasks.yml"

- name: "Ensure /root/.ssh exists"
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: "Ensure private SSH key for {{ r10k_variant }} is present"
  ansible.builtin.copy:
    content: "{{ r10k_ssh_private_key | trim }}\n"
    dest: /root/.ssh/id_ed25519
    owner: root
    group: root
    mode: '0600'
  no_log: true

- name: "Ensure public SSH key for {{ r10k_variant }} is present"
  ansible.builtin.copy:
    content: "{{ r10k_ssh_public_key }}"
    dest: /root/.ssh/id_ed25519.pub
    owner: root
    group: root
    mode: '0644'

- name: "Ensure Git server host key in known_hosts is present"
  ansible.builtin.known_hosts:
    name: "{{ git_server }}"
    state: present
    key: "{{ lookup('ansible.builtin.pipe', 'ssh-keyscan -t ed25519 ' + git_server) }}"

- name: "Ensure {{ puppet_server_package }} {{ puppet_version }} is installed"
  ansible.builtin.package:
    name:
      - "{{ puppet_server_package }}"
    state: present

- name: "Ensure git is installed"
  ansible.builtin.package:
    name: git
    state: present

- name: "Ensure /etc/puppetlabs/r10k exists"
  ansible.builtin.file:
    path: /etc/puppetlabs/r10k
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: "Ensure r10k.yaml configuration file is rendered from template"
  ansible.builtin.template:
    src: r10k.yaml.j2
    dest: /etc/puppetlabs/r10k/r10k.yaml
    owner: root
    group: root
    mode: '0644'
  register: r10k_deploy_result

- name: "Trigger {{ r10k_variant }} deploy"
  ansible.builtin.command: >
    {{ r10k_path }} --config /etc/puppetlabs/r10k/r10k.yaml deploy environment -pv
  when: r10k_deploy_result.changed

- name: "Ensure {{ puppet_server_service }} is started and enabled"
  ansible.builtin.service:
    name: "{{ puppet_server_service }}"
    state: "{{ puppet_server_service_state }}"
    enabled: "{{ puppet_server_service_enabled }}"
  when: puppet_server_service_manage
